### ISSUE TITLE
[consul] Simplify the IAMGroupMapping setting 

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-bastionsshkey#50]
Wouldn't something like this be clearer?

```yaml
  GroupMapping:
    - groupNumber1:
      IAMPath: /nubis/admins/
      ConsulPath: global-admins
    - groupNumber2:
      LDAPGroup: groupNumber2
      IAMPath: /nubis/foo/
      ConsulPath: foo
```

Compared with:

```yaml
  IAMGroupMapping:
    - Group1:
      LDAPGroup: groupNumber1
      IAMPath: /nubis/admin/
      ConsulPath: global-admins
    - Group2:
      LDAPGroup: groupNumber2
      IAMPath: /nubis/foo/
      ConsulPath: foo
```
